QLCuocDienThoai/QLCuocDienThoai_User/Controllers/ThongTinSuDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLCuocDienThoai_User.DAO;

namespace QLCuocDienThoai_User.Controllers
{
    public class ThongTinSuDungController : Controller
    {
        // GET: ThongTinSuDung
        public ActionResult Index(string sdt)
        {
            var dao = new ThongTinSuDung();
            var model = dao.GetThongTinSuDung(sdt);
            return View(model);
        }
    }
}

QLCuocDienThoai/QLCuocDienThoai_User/Views/ThongTinSuDung/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Thông tin sử dụng</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="col-lg-12">
    <div class="panel panel-default">
        <!-- /.panel-heading -->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <!--------------------------------------------- Search And Add ------------------------------------------------->
                    <div class="form-group">
                        @using (Html.BeginForm("Index", "ThongTinSuDung", FormMethod.Get))
                        {
                            <label>Nhập Số điện thoại:</label>
                            <input type="text" , name="sdt">
                            <button type="submit" class="btn btn-primary">Tìm Kiếm</button>
                        }
                    </div>
                    <!------------------------------------------- Loading Edit Delete ----------------------------------------------->
                    <thead>
                        <tr>
                            <th>Thời gian bắt đầu</th>
                            <th>Thời gian kế thúc</th>
                            <th>Số phút</th>
                            <th>Cước phí</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td> @item.Tgbd</td>
                            <td> @item.Tgkt</td>
                            <td> @item.Sophut</td>
                            <td> @item.Cuocphi</td>
                        </tr>
                        }
                    </tbody>
                </table>
                
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>